let express = require('express');
let router = express.Router();
const passport = require('passport');
const orders = require('../controllers/orders');
router.post('/book', passport.authenticate('jwt'), orders.book);
router.post('/accept/:orderId', passport.authenticate('jwt'), orders.acceptOrder);
router.post('/update/:orderId', passport.authenticate('jwt'), orders.setOrderInProgressOrDone);
router.post('/cancel/:orderId', passport.authenticate('jwt'), orders.cancelOrder);
router.get('/', passport.authenticate('jwt'), orders.getOrders);
module.exports = router;